### ISSUE TITLE
Crash bro

### ISSUE THREAD

**Issue by 846793234** [maxamula/dx11hk#1]

**Comment by maxamula** [comment]
Hi, this is x64 libraty only. However it is still possible to use VMT method to hook Present(IDXGISwapChain* pSwapchain, UINT SyncInterval, UINT Flags) for x86 processes.
To prevent errors you have to specify _stdcall calling convencion for your detour.

```
typedef HRESULT(__stdcall*fnPresent_t)(IDXGISwapChain* pSwapchain, UINT SyncInterval, UINT Flags);
fnPresent_t orig;

HRESULT __stdcall hkPresent(IDXGISwapChain* pSwapchain, UINT SyncInterval, UINT Flags)
{
    ID3D11Device* device;
    pSwapchain->GetDevice(IID_PPV_ARGS(&device));
// render your own stuff here
    return orig(pSwapchain, SyncInterval, Flags);
}
```

Note that VMT method is slow and it might take a few seconds to find original swapchain vitrual method table.
Hope that helps:)
